version: 2.0
jobs:
  test:
    working_directory: ~/repo
    docker:
    - image: circleci/python:3.7.0-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "setup.py" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          python -m venv venv
          . venv/bin/activate
          python3 setup.py install
          pip install tox

    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "setup.py" }}

    - run:
        command: |
          . venv/bin/activate
          tox

    - run:
        name: collect coverage
        command: |
          bash <(curl -s https://codecov.io/bash)

    - store_artifacts:
        path: test-reports
        destination: test-reports

  release_pypi:
    docker:
    - image: circleci/python:3.7.0-node
    steps:
      - checkout
      - run:
          name: setup venv
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: install twine
          command: |
            . venv/bin/activate
            pip install twine
      - run:
          name: sdist
          command: |
            . venv/bin/activate
            python setup.py sdist
      - run:
          name: upload
          command: |
            . venv/bin/activate
            twine upload dist/asyncy-*.tar.gz
  release_brew:
    macos:
      xcode: "9.0"
    steps:
      - run:
          name: install brew
          command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run:
          name: install python
          command: brew install python
      - checkout
      - run:
          name: create brew pr
          command: bash ./scripts/update_brew.sh $CIRCLE_TAG
#  release_snap:
#    docker:
#      - image: cibuilds/snapcraft:stable
#    steps:
#      - checkout
#      - run:
#          name: apt-get update
#          command: apt-get update
#      - run:
#          name: create snapcraft.yaml
#          command: |
#            echo "
#            name: asyncy
#            version: $CIRCLE_TAG
#            summary: Asyncy CLI
#            description: Asyncy CLI
#            grade: devel
#            confinement: devmode
#            base: core18
#
#            apps:
#              asyncy:
#                command: bin/asyncy
#                environment:
#                  LANG: C.UTF-8
#                  LC_ALL: C.UTF-8
#
#            parts:
#              asyncy:
#                plugin: python
#                python-version: python3
#                python-packages:
#                - asyncy==$CIRCLE_TAG
#            " > snapcraft.yaml
#      - run:
#          name: build snap
#          command: snapcraft
#      - run:
#          name: install snap
#          command: snap install asyncy_${CIRCLE_TAG}_amd64.snap --dangerous --devmode
#      - run:
#          name: check version
#          command: asyncy version | grep ${CIRCLE_TAG}
#      - run:
#          name: snapcraft login
#          command: echo $SNAPCRAFT_LOGIN | snapcraft login --with -
#      - run:
#          name: snapcraft push
#          command: snapcraft push --release edge asyncy_${CIRCLE_TAG}_amd64.snap
workflows:
  version: 2
  build-test-deploy:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - release_pypi:
        requires:
          - test
        filters:
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+$/
          branches:
            ignore: /.*/
#    - release_snap:
#        requires:
#          - release_pypi
#        filters:
#          tags:
#            only: /^[0-9]+\.[0-9]+\.[0-9]+$/
#          branches:
#            ignore: /.*/
    - release_brew
#        requires:
#        - release_pypi
#        filters:
#          tags:
#            only: /^[0-9]+\.[0-9]+\.[0-9]+$/
#          branches:
#            ignore: /.*/
