name: story
version: git
version-script: git describe --tags
summary: Story CLI
description: Core toolkit to interact with Storyscript Cloud
grade: stable
confinement: strict
base: core18

apps:
  story:
    command: bin/story
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

parts:
  storyscript:
    plugin: python
    python-version: python3
    source: https://github.com/storyscript/storyscript.git
    source-tag: 0.18.2
  story:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - libbz2-1.0
      - libdb5.3
      - liblzma5
      - libncursesw5
      - libtinfo5
      - zlib1g
